-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hls_real2xfft is
port (
    ap_local_block : OUT STD_LOGIC;
    ap_local_deadlock : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    din_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    dout_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    din_TVALID : IN STD_LOGIC;
    din_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    dout_TVALID : OUT STD_LOGIC;
    dout_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of hls_real2xfft is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hls_real2xfft_hls_real2xfft,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.150000,HLS_SYN_LAT=1549,HLS_SYN_TPT=512,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=1589,HLS_SYN_LUT=1098,HLS_VERSION=2021_2}";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal data2window_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal data2window_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal data2window_V_2_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal data2window_V_2_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal windowed_V_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal windowed_V_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal windowed_V_1_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal windowed_V_1_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_delay_proc1_U0_ap_start : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_ap_done : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_ap_continue : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_ap_idle : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_ap_ready : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_nodelay_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_delay_proc1_U0_nodelay_V_write : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_delayed_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_delay_proc1_U0_delayed_V_write : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_delayed_V_1_din : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_delay_proc1_U0_delayed_V_1_write : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_start_out : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_start_write : STD_LOGIC;
    signal Loop_sliding_win_delay_proc1_U0_din_TREADY : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_ap_start : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_ap_done : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_ap_continue : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_ap_idle : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_ap_ready : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_delayed_V_read : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_delayed_V_1_read : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_nodelay_V_read : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_nodelay_V_1_read : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_2_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0 : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_2_we0 : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_2_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal Loop_sliding_win_output_proc2_U0_data2window_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Loop_sliding_win_output_proc2_U0_data2window_V_ce0 : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_we0 : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_data2window_V : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_data2window_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_data2window_V : STD_LOGIC;
    signal ap_channel_done_data2window_V_2 : STD_LOGIC;
    signal Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_data2window_V_2 : STD_LOGIC := '0';
    signal ap_sync_channel_write_data2window_V_2 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_windowed_V_1 : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_windowed_V_1 : STD_LOGIC := '0';
    signal ap_sync_channel_write_windowed_V_1 : STD_LOGIC;
    signal ap_channel_done_windowed_V : STD_LOGIC;
    signal window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_windowed_V : STD_LOGIC := '0';
    signal ap_sync_channel_write_windowed_V : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_ap_start : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_ap_done : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_ap_continue : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_ap_idle : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_ap_ready : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_windowed_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Loop_real2xfft_output_proc3_U0_windowed_V_ce0 : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_windowed_V_1_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0 : STD_LOGIC;
    signal Loop_real2xfft_output_proc3_U0_dout_TDATA : STD_LOGIC_VECTOR (47 downto 0);
    signal Loop_real2xfft_output_proc3_U0_dout_TVALID : STD_LOGIC;
    signal data2window_V_2_i_full_n : STD_LOGIC;
    signal data2window_V_2_t_empty_n : STD_LOGIC;
    signal data2window_V_i_full_n : STD_LOGIC;
    signal data2window_V_t_empty_n : STD_LOGIC;
    signal windowed_V_i_full_n : STD_LOGIC;
    signal windowed_V_t_empty_n : STD_LOGIC;
    signal windowed_V_1_i_full_n : STD_LOGIC;
    signal windowed_V_1_t_empty_n : STD_LOGIC;
    signal delayed_V_full_n : STD_LOGIC;
    signal delayed_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal delayed_V_empty_n : STD_LOGIC;
    signal nodelay_V_full_n : STD_LOGIC;
    signal nodelay_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal nodelay_V_empty_n : STD_LOGIC;
    signal nodelay_V_1_full_n : STD_LOGIC;
    signal nodelay_V_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal nodelay_V_1_empty_n : STD_LOGIC;
    signal delayed_V_1_full_n : STD_LOGIC;
    signal delayed_V_1_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal delayed_V_1_empty_n : STD_LOGIC;
    signal start_for_Loop_sliding_win_output_proc2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_sliding_win_output_proc2_U0_full_n : STD_LOGIC;
    signal start_for_Loop_sliding_win_output_proc2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Loop_sliding_win_output_proc2_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component hls_real2xfft_Loop_sliding_win_delay_proc1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        din_TVALID : IN STD_LOGIC;
        nodelay_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_full_n : IN STD_LOGIC;
        nodelay_V_write : OUT STD_LOGIC;
        nodelay_V_1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_1_full_n : IN STD_LOGIC;
        nodelay_V_1_write : OUT STD_LOGIC;
        delayed_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_full_n : IN STD_LOGIC;
        delayed_V_write : OUT STD_LOGIC;
        delayed_V_1_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_1_full_n : IN STD_LOGIC;
        delayed_V_1_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        din_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        din_TREADY : OUT STD_LOGIC );
    end component;


    component hls_real2xfft_Loop_sliding_win_output_proc2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        delayed_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_empty_n : IN STD_LOGIC;
        delayed_V_read : OUT STD_LOGIC;
        delayed_V_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        delayed_V_1_empty_n : IN STD_LOGIC;
        delayed_V_1_read : OUT STD_LOGIC;
        nodelay_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_empty_n : IN STD_LOGIC;
        nodelay_V_read : OUT STD_LOGIC;
        nodelay_V_1_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        nodelay_V_1_empty_n : IN STD_LOGIC;
        nodelay_V_1_read : OUT STD_LOGIC;
        data2window_V_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        data2window_V_2_ce0 : OUT STD_LOGIC;
        data2window_V_2_we0 : OUT STD_LOGIC;
        data2window_V_2_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        data2window_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        data2window_V_ce0 : OUT STD_LOGIC;
        data2window_V_we0 : OUT STD_LOGIC;
        data2window_V_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_real2xfft_window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        indata_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        indata_0_ce0 : OUT STD_LOGIC;
        indata_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        indata_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        indata_1_ce0 : OUT STD_LOGIC;
        indata_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        outdata_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        outdata_0_ce0 : OUT STD_LOGIC;
        outdata_0_we0 : OUT STD_LOGIC;
        outdata_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        outdata_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        outdata_1_ce0 : OUT STD_LOGIC;
        outdata_1_we0 : OUT STD_LOGIC;
        outdata_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component hls_real2xfft_Loop_real2xfft_output_proc3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        dout_TREADY : IN STD_LOGIC;
        windowed_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        windowed_V_ce0 : OUT STD_LOGIC;
        windowed_V_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        windowed_V_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        windowed_V_1_ce0 : OUT STD_LOGIC;
        windowed_V_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        dout_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
        dout_TVALID : OUT STD_LOGIC );
    end component;


    component hls_real2xfft_data2window_V_RAM_AUTO_2R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_we0 : IN STD_LOGIC;
        i_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        i_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_we0 : IN STD_LOGIC;
        t_d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        t_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component hls_real2xfft_fifo_w16_d256_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_real2xfft_fifo_w16_d512_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component hls_real2xfft_start_for_Loop_sliding_win_output_proc2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    data2window_V_U : component hls_real2xfft_data2window_V_RAM_AUTO_2R1W
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_sliding_win_output_proc2_U0_data2window_V_address0,
        i_ce0 => Loop_sliding_win_output_proc2_U0_data2window_V_ce0,
        i_we0 => Loop_sliding_win_output_proc2_U0_data2window_V_we0,
        i_d0 => Loop_sliding_win_output_proc2_U0_data2window_V_d0,
        i_q0 => data2window_V_i_q0,
        t_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0,
        t_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => data2window_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => data2window_V_i_full_n,
        i_write => ap_channel_done_data2window_V,
        t_empty_n => data2window_V_t_empty_n,
        t_read => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready);

    data2window_V_2_U : component hls_real2xfft_data2window_V_RAM_AUTO_2R1W
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_address0,
        i_ce0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0,
        i_we0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_we0,
        i_d0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_d0,
        i_q0 => data2window_V_2_i_q0,
        t_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0,
        t_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => data2window_V_2_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => data2window_V_2_i_full_n,
        i_write => ap_channel_done_data2window_V_2,
        t_empty_n => data2window_V_2_t_empty_n,
        t_read => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready);

    windowed_V_U : component hls_real2xfft_data2window_V_RAM_AUTO_2R1W
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0,
        i_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0,
        i_we0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0,
        i_d0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0,
        i_q0 => windowed_V_i_q0,
        t_address0 => Loop_real2xfft_output_proc3_U0_windowed_V_address0,
        t_ce0 => Loop_real2xfft_output_proc3_U0_windowed_V_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => windowed_V_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => windowed_V_i_full_n,
        i_write => ap_channel_done_windowed_V,
        t_empty_n => windowed_V_t_empty_n,
        t_read => Loop_real2xfft_output_proc3_U0_ap_ready);

    windowed_V_1_U : component hls_real2xfft_data2window_V_RAM_AUTO_2R1W
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0,
        i_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0,
        i_we0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0,
        i_d0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0,
        i_q0 => windowed_V_1_i_q0,
        t_address0 => Loop_real2xfft_output_proc3_U0_windowed_V_1_address0,
        t_ce0 => Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0,
        t_we0 => ap_const_logic_0,
        t_d0 => ap_const_lv16_0,
        t_q0 => windowed_V_1_t_q0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => windowed_V_1_i_full_n,
        i_write => ap_channel_done_windowed_V_1,
        t_empty_n => windowed_V_1_t_empty_n,
        t_read => Loop_real2xfft_output_proc3_U0_ap_ready);

    Loop_sliding_win_delay_proc1_U0 : component hls_real2xfft_Loop_sliding_win_delay_proc1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_sliding_win_delay_proc1_U0_ap_start,
        start_full_n => start_for_Loop_sliding_win_output_proc2_U0_full_n,
        ap_done => Loop_sliding_win_delay_proc1_U0_ap_done,
        ap_continue => Loop_sliding_win_delay_proc1_U0_ap_continue,
        ap_idle => Loop_sliding_win_delay_proc1_U0_ap_idle,
        ap_ready => Loop_sliding_win_delay_proc1_U0_ap_ready,
        din_TVALID => din_TVALID,
        nodelay_V_din => Loop_sliding_win_delay_proc1_U0_nodelay_V_din,
        nodelay_V_full_n => nodelay_V_full_n,
        nodelay_V_write => Loop_sliding_win_delay_proc1_U0_nodelay_V_write,
        nodelay_V_1_din => Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din,
        nodelay_V_1_full_n => nodelay_V_1_full_n,
        nodelay_V_1_write => Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write,
        delayed_V_din => Loop_sliding_win_delay_proc1_U0_delayed_V_din,
        delayed_V_full_n => delayed_V_full_n,
        delayed_V_write => Loop_sliding_win_delay_proc1_U0_delayed_V_write,
        delayed_V_1_din => Loop_sliding_win_delay_proc1_U0_delayed_V_1_din,
        delayed_V_1_full_n => delayed_V_1_full_n,
        delayed_V_1_write => Loop_sliding_win_delay_proc1_U0_delayed_V_1_write,
        start_out => Loop_sliding_win_delay_proc1_U0_start_out,
        start_write => Loop_sliding_win_delay_proc1_U0_start_write,
        din_TDATA => din_TDATA,
        din_TREADY => Loop_sliding_win_delay_proc1_U0_din_TREADY);

    Loop_sliding_win_output_proc2_U0 : component hls_real2xfft_Loop_sliding_win_output_proc2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_sliding_win_output_proc2_U0_ap_start,
        ap_done => Loop_sliding_win_output_proc2_U0_ap_done,
        ap_continue => Loop_sliding_win_output_proc2_U0_ap_continue,
        ap_idle => Loop_sliding_win_output_proc2_U0_ap_idle,
        ap_ready => Loop_sliding_win_output_proc2_U0_ap_ready,
        delayed_V_dout => delayed_V_dout,
        delayed_V_empty_n => delayed_V_empty_n,
        delayed_V_read => Loop_sliding_win_output_proc2_U0_delayed_V_read,
        delayed_V_1_dout => delayed_V_1_dout,
        delayed_V_1_empty_n => delayed_V_1_empty_n,
        delayed_V_1_read => Loop_sliding_win_output_proc2_U0_delayed_V_1_read,
        nodelay_V_dout => nodelay_V_dout,
        nodelay_V_empty_n => nodelay_V_empty_n,
        nodelay_V_read => Loop_sliding_win_output_proc2_U0_nodelay_V_read,
        nodelay_V_1_dout => nodelay_V_1_dout,
        nodelay_V_1_empty_n => nodelay_V_1_empty_n,
        nodelay_V_1_read => Loop_sliding_win_output_proc2_U0_nodelay_V_1_read,
        data2window_V_2_address0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_address0,
        data2window_V_2_ce0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0,
        data2window_V_2_we0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_we0,
        data2window_V_2_d0 => Loop_sliding_win_output_proc2_U0_data2window_V_2_d0,
        data2window_V_address0 => Loop_sliding_win_output_proc2_U0_data2window_V_address0,
        data2window_V_ce0 => Loop_sliding_win_output_proc2_U0_data2window_V_ce0,
        data2window_V_we0 => Loop_sliding_win_output_proc2_U0_data2window_V_we0,
        data2window_V_d0 => Loop_sliding_win_output_proc2_U0_data2window_V_d0);

    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0 : component hls_real2xfft_window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start,
        ap_done => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done,
        ap_continue => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue,
        ap_idle => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle,
        ap_ready => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready,
        indata_0_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0,
        indata_0_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0,
        indata_0_q0 => data2window_V_t_q0,
        indata_1_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0,
        indata_1_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0,
        indata_1_q0 => data2window_V_2_t_q0,
        outdata_0_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0,
        outdata_0_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0,
        outdata_0_we0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0,
        outdata_0_d0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0,
        outdata_1_address0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0,
        outdata_1_ce0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0,
        outdata_1_we0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0,
        outdata_1_d0 => window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0);

    Loop_real2xfft_output_proc3_U0 : component hls_real2xfft_Loop_real2xfft_output_proc3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_real2xfft_output_proc3_U0_ap_start,
        ap_done => Loop_real2xfft_output_proc3_U0_ap_done,
        ap_continue => Loop_real2xfft_output_proc3_U0_ap_continue,
        ap_idle => Loop_real2xfft_output_proc3_U0_ap_idle,
        ap_ready => Loop_real2xfft_output_proc3_U0_ap_ready,
        dout_TREADY => dout_TREADY,
        windowed_V_address0 => Loop_real2xfft_output_proc3_U0_windowed_V_address0,
        windowed_V_ce0 => Loop_real2xfft_output_proc3_U0_windowed_V_ce0,
        windowed_V_q0 => windowed_V_t_q0,
        windowed_V_1_address0 => Loop_real2xfft_output_proc3_U0_windowed_V_1_address0,
        windowed_V_1_ce0 => Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0,
        windowed_V_1_q0 => windowed_V_1_t_q0,
        dout_TDATA => Loop_real2xfft_output_proc3_U0_dout_TDATA,
        dout_TVALID => Loop_real2xfft_output_proc3_U0_dout_TVALID);

    delayed_V_U : component hls_real2xfft_fifo_w16_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sliding_win_delay_proc1_U0_delayed_V_din,
        if_full_n => delayed_V_full_n,
        if_write => Loop_sliding_win_delay_proc1_U0_delayed_V_write,
        if_dout => delayed_V_dout,
        if_empty_n => delayed_V_empty_n,
        if_read => Loop_sliding_win_output_proc2_U0_delayed_V_read);

    nodelay_V_U : component hls_real2xfft_fifo_w16_d512_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sliding_win_delay_proc1_U0_nodelay_V_din,
        if_full_n => nodelay_V_full_n,
        if_write => Loop_sliding_win_delay_proc1_U0_nodelay_V_write,
        if_dout => nodelay_V_dout,
        if_empty_n => nodelay_V_empty_n,
        if_read => Loop_sliding_win_output_proc2_U0_nodelay_V_read);

    nodelay_V_1_U : component hls_real2xfft_fifo_w16_d512_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din,
        if_full_n => nodelay_V_1_full_n,
        if_write => Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write,
        if_dout => nodelay_V_1_dout,
        if_empty_n => nodelay_V_1_empty_n,
        if_read => Loop_sliding_win_output_proc2_U0_nodelay_V_1_read);

    delayed_V_1_U : component hls_real2xfft_fifo_w16_d256_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_sliding_win_delay_proc1_U0_delayed_V_1_din,
        if_full_n => delayed_V_1_full_n,
        if_write => Loop_sliding_win_delay_proc1_U0_delayed_V_1_write,
        if_dout => delayed_V_1_dout,
        if_empty_n => delayed_V_1_empty_n,
        if_read => Loop_sliding_win_output_proc2_U0_delayed_V_1_read);

    start_for_Loop_sliding_win_output_proc2_U0_U : component hls_real2xfft_start_for_Loop_sliding_win_output_proc2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Loop_sliding_win_output_proc2_U0_din,
        if_full_n => start_for_Loop_sliding_win_output_proc2_U0_full_n,
        if_write => Loop_sliding_win_delay_proc1_U0_start_write,
        if_dout => start_for_Loop_sliding_win_output_proc2_U0_dout,
        if_empty_n => start_for_Loop_sliding_win_output_proc2_U0_empty_n,
        if_read => Loop_sliding_win_output_proc2_U0_ap_ready);





    ap_sync_reg_channel_write_data2window_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_data2window_V <= ap_const_logic_0;
            else
                if (((Loop_sliding_win_output_proc2_U0_ap_done and Loop_sliding_win_output_proc2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_data2window_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_data2window_V <= ap_sync_channel_write_data2window_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_data2window_V_2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_data2window_V_2 <= ap_const_logic_0;
            else
                if (((Loop_sliding_win_output_proc2_U0_ap_done and Loop_sliding_win_output_proc2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_data2window_V_2 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_data2window_V_2 <= ap_sync_channel_write_data2window_V_2;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_windowed_V_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_windowed_V <= ap_const_logic_0;
            else
                if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done and window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_windowed_V <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_windowed_V <= ap_sync_channel_write_windowed_V;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_windowed_V_1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_windowed_V_1 <= ap_const_logic_0;
            else
                if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done and window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_windowed_V_1 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_windowed_V_1 <= ap_sync_channel_write_windowed_V_1;
                end if; 
            end if;
        end if;
    end process;

    Loop_real2xfft_output_proc3_U0_ap_continue <= ap_const_logic_1;
    Loop_real2xfft_output_proc3_U0_ap_start <= (windowed_V_t_empty_n and windowed_V_1_t_empty_n);
    Loop_sliding_win_delay_proc1_U0_ap_continue <= ap_const_logic_1;
    Loop_sliding_win_delay_proc1_U0_ap_start <= ap_start;
    Loop_sliding_win_output_proc2_U0_ap_continue <= (ap_sync_channel_write_data2window_V_2 and ap_sync_channel_write_data2window_V);
    Loop_sliding_win_output_proc2_U0_ap_start <= start_for_Loop_sliding_win_output_proc2_U0_empty_n;
    Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n <= data2window_V_2_i_full_n;
    Loop_sliding_win_output_proc2_U0_data2window_V_full_n <= data2window_V_i_full_n;
    ap_channel_done_data2window_V <= ((ap_sync_reg_channel_write_data2window_V xor ap_const_logic_1) and Loop_sliding_win_output_proc2_U0_ap_done);
    ap_channel_done_data2window_V_2 <= ((ap_sync_reg_channel_write_data2window_V_2 xor ap_const_logic_1) and Loop_sliding_win_output_proc2_U0_ap_done);
    ap_channel_done_windowed_V <= (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done and (ap_sync_reg_channel_write_windowed_V xor ap_const_logic_1));
    ap_channel_done_windowed_V_1 <= (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done and (ap_sync_reg_channel_write_windowed_V_1 xor ap_const_logic_1));
    ap_done <= Loop_real2xfft_output_proc3_U0_ap_done;
    ap_idle <= (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle and (windowed_V_1_t_empty_n xor ap_const_logic_1) and (windowed_V_t_empty_n xor ap_const_logic_1) and (data2window_V_t_empty_n xor ap_const_logic_1) and (data2window_V_2_t_empty_n xor ap_const_logic_1) and Loop_sliding_win_output_proc2_U0_ap_idle and Loop_sliding_win_delay_proc1_U0_ap_idle and Loop_real2xfft_output_proc3_U0_ap_idle);
    ap_local_block <= ap_const_logic_0;
    ap_local_deadlock <= ap_const_logic_0;
    ap_ready <= Loop_sliding_win_delay_proc1_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_channel_write_data2window_V <= ((ap_channel_done_data2window_V and Loop_sliding_win_output_proc2_U0_data2window_V_full_n) or ap_sync_reg_channel_write_data2window_V);
    ap_sync_channel_write_data2window_V_2 <= ((ap_channel_done_data2window_V_2 and Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n) or ap_sync_reg_channel_write_data2window_V_2);
    ap_sync_channel_write_windowed_V <= ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n and ap_channel_done_windowed_V) or ap_sync_reg_channel_write_windowed_V);
    ap_sync_channel_write_windowed_V_1 <= ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n and ap_channel_done_windowed_V_1) or ap_sync_reg_channel_write_windowed_V_1);
    din_TREADY <= Loop_sliding_win_delay_proc1_U0_din_TREADY;
    dout_TDATA <= Loop_real2xfft_output_proc3_U0_dout_TDATA;
    dout_TVALID <= Loop_real2xfft_output_proc3_U0_dout_TVALID;
    start_for_Loop_sliding_win_output_proc2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue <= (ap_sync_channel_write_windowed_V_1 and ap_sync_channel_write_windowed_V);
    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start <= (data2window_V_t_empty_n and data2window_V_2_t_empty_n);
    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n <= windowed_V_i_full_n;
    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n <= windowed_V_1_i_full_n;
end behav;
