# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wdb87/Documents/LabA/Using_IP_with_Zynq/lab2/project_1/project_1.srcs/sources_1/bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_xfft2real_0_0/Zynq_RealFFT_hls_xfft2real_0_0.xci
# IP: The module: 'Zynq_RealFFT_hls_xfft2real_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wdb87/Documents/LabA/Using_IP_with_Zynq/lab2/project_1/project_1.gen/sources_1/bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_xfft2real_0_0/constraints/hls_xfft2real_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_RealFFT_hls_xfft2real_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/wdb87/Documents/LabA/Using_IP_with_Zynq/lab2/project_1/project_1.srcs/sources_1/bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_xfft2real_0_0/Zynq_RealFFT_hls_xfft2real_0_0.xci
# IP: The module: 'Zynq_RealFFT_hls_xfft2real_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wdb87/Documents/LabA/Using_IP_with_Zynq/lab2/project_1/project_1.gen/sources_1/bd/Zynq_RealFFT/ip/Zynq_RealFFT_hls_xfft2real_0_0/constraints/hls_xfft2real_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Zynq_RealFFT_hls_xfft2real_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
