// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_xfft2real_Loop_realfft_be_descramble_proc2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        descramble_buf_M_real_V_1_address0,
        descramble_buf_M_real_V_1_ce0,
        descramble_buf_M_real_V_1_q0,
        descramble_buf_M_imag_V_1_address0,
        descramble_buf_M_imag_V_1_ce0,
        descramble_buf_M_imag_V_1_q0,
        real_spectrum_lo_i_din,
        real_spectrum_lo_i_full_n,
        real_spectrum_lo_i_write,
        real_spectrum_hi_buf_M_real_V_address0,
        real_spectrum_hi_buf_M_real_V_ce0,
        real_spectrum_hi_buf_M_real_V_we0,
        real_spectrum_hi_buf_M_real_V_d0,
        real_spectrum_hi_buf_M_imag_V_address0,
        real_spectrum_hi_buf_M_imag_V_ce0,
        real_spectrum_hi_buf_M_imag_V_we0,
        real_spectrum_hi_buf_M_imag_V_d0,
        descramble_buf_M_real_V_address0,
        descramble_buf_M_real_V_ce0,
        descramble_buf_M_real_V_q0,
        descramble_buf_M_imag_V_address0,
        descramble_buf_M_imag_V_ce0,
        descramble_buf_M_imag_V_q0,
        twid_rom_M_real_V_address0,
        twid_rom_M_real_V_ce0,
        twid_rom_M_real_V_q0,
        twid_rom_M_imag_V_address0,
        twid_rom_M_imag_V_ce0,
        twid_rom_M_imag_V_q0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output  [7:0] descramble_buf_M_real_V_1_address0;
output   descramble_buf_M_real_V_1_ce0;
input  [15:0] descramble_buf_M_real_V_1_q0;
output  [7:0] descramble_buf_M_imag_V_1_address0;
output   descramble_buf_M_imag_V_1_ce0;
input  [15:0] descramble_buf_M_imag_V_1_q0;
output  [31:0] real_spectrum_lo_i_din;
input   real_spectrum_lo_i_full_n;
output   real_spectrum_lo_i_write;
output  [7:0] real_spectrum_hi_buf_M_real_V_address0;
output   real_spectrum_hi_buf_M_real_V_ce0;
output   real_spectrum_hi_buf_M_real_V_we0;
output  [15:0] real_spectrum_hi_buf_M_real_V_d0;
output  [7:0] real_spectrum_hi_buf_M_imag_V_address0;
output   real_spectrum_hi_buf_M_imag_V_ce0;
output   real_spectrum_hi_buf_M_imag_V_we0;
output  [15:0] real_spectrum_hi_buf_M_imag_V_d0;
output  [7:0] descramble_buf_M_real_V_address0;
output   descramble_buf_M_real_V_ce0;
input  [15:0] descramble_buf_M_real_V_q0;
output  [7:0] descramble_buf_M_imag_V_address0;
output   descramble_buf_M_imag_V_ce0;
input  [15:0] descramble_buf_M_imag_V_q0;
output  [7:0] twid_rom_M_real_V_address0;
output   twid_rom_M_real_V_ce0;
input  [14:0] twid_rom_M_real_V_q0;
output  [7:0] twid_rom_M_imag_V_address0;
output   twid_rom_M_imag_V_ce0;
input  [15:0] twid_rom_M_imag_V_q0;

reg ap_done;
reg ap_idle;
reg start_write;
reg[7:0] descramble_buf_M_real_V_1_address0;
reg descramble_buf_M_real_V_1_ce0;
reg[7:0] descramble_buf_M_imag_V_1_address0;
reg descramble_buf_M_imag_V_1_ce0;
reg real_spectrum_lo_i_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [15:0] descramble_buf_M_real_V_1_load_reg_94;
wire    ap_CS_fsm_state3;
reg   [15:0] descramble_buf_M_imag_V_1_load_reg_99;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_idle;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_ready;
wire   [31:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_din;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_write;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_ce0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_ce0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_we0;
wire   [15:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_d0;
wire   [7:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_address0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_ce0;
wire    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_we0;
wire   [15:0] grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_d0;
reg    grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    ap_block_state1;
wire    ap_CS_fsm_state2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg = 1'b0;
end

hls_xfft2real_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start),
    .ap_done(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done),
    .ap_idle(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_idle),
    .ap_ready(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_ready),
    .real_spectrum_lo_i_din(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_din),
    .real_spectrum_lo_i_full_n(real_spectrum_lo_i_full_n),
    .real_spectrum_lo_i_write(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_write),
    .descramble_buf_M_real_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_address0),
    .descramble_buf_M_real_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_ce0),
    .descramble_buf_M_real_V_q0(descramble_buf_M_real_V_q0),
    .descramble_buf_M_imag_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_address0),
    .descramble_buf_M_imag_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_ce0),
    .descramble_buf_M_imag_V_q0(descramble_buf_M_imag_V_q0),
    .descramble_buf_M_imag_V_1_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_address0),
    .descramble_buf_M_imag_V_1_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_ce0),
    .descramble_buf_M_imag_V_1_q0(descramble_buf_M_imag_V_1_q0),
    .descramble_buf_M_real_V_1_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_address0),
    .descramble_buf_M_real_V_1_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_ce0),
    .descramble_buf_M_real_V_1_q0(descramble_buf_M_real_V_1_q0),
    .twid_rom_M_real_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_address0),
    .twid_rom_M_real_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_ce0),
    .twid_rom_M_real_V_q0(twid_rom_M_real_V_q0),
    .twid_rom_M_imag_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_address0),
    .twid_rom_M_imag_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_ce0),
    .twid_rom_M_imag_V_q0(twid_rom_M_imag_V_q0),
    .descramble_buf_M_imag_V_1_load(descramble_buf_M_imag_V_1_load_reg_99),
    .descramble_buf_M_real_V_1_load(descramble_buf_M_real_V_1_load_reg_94),
    .real_spectrum_hi_buf_M_real_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_address0),
    .real_spectrum_hi_buf_M_real_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_ce0),
    .real_spectrum_hi_buf_M_real_V_we0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_we0),
    .real_spectrum_hi_buf_M_real_V_d0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_d0),
    .real_spectrum_hi_buf_M_imag_V_address0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_address0),
    .real_spectrum_hi_buf_M_imag_V_ce0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_ce0),
    .real_spectrum_hi_buf_M_imag_V_we0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_we0),
    .real_spectrum_hi_buf_M_imag_V_d0(grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & (grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_ready == 1'b1)) begin
            grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        descramble_buf_M_imag_V_1_load_reg_99 <= descramble_buf_M_imag_V_1_q0;
        descramble_buf_M_real_V_1_load_reg_94 <= descramble_buf_M_real_V_1_q0;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        descramble_buf_M_imag_V_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        descramble_buf_M_imag_V_1_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_address0;
    end else begin
        descramble_buf_M_imag_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        descramble_buf_M_imag_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        descramble_buf_M_imag_V_1_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_1_ce0;
    end else begin
        descramble_buf_M_imag_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        descramble_buf_M_real_V_1_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        descramble_buf_M_real_V_1_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_address0;
    end else begin
        descramble_buf_M_real_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state3) | (~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        descramble_buf_M_real_V_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        descramble_buf_M_real_V_1_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_1_ce0;
    end else begin
        descramble_buf_M_real_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        real_spectrum_lo_i_write = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_write;
    end else begin
        real_spectrum_lo_i_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign descramble_buf_M_imag_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_address0;

assign descramble_buf_M_imag_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_imag_V_ce0;

assign descramble_buf_M_real_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_address0;

assign descramble_buf_M_real_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_descramble_buf_M_real_V_ce0;

assign grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_ap_start_reg;

assign real_spectrum_hi_buf_M_imag_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_address0;

assign real_spectrum_hi_buf_M_imag_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_ce0;

assign real_spectrum_hi_buf_M_imag_V_d0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_d0;

assign real_spectrum_hi_buf_M_imag_V_we0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_imag_V_we0;

assign real_spectrum_hi_buf_M_real_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_address0;

assign real_spectrum_hi_buf_M_real_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_ce0;

assign real_spectrum_hi_buf_M_real_V_d0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_d0;

assign real_spectrum_hi_buf_M_real_V_we0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_hi_buf_M_real_V_we0;

assign real_spectrum_lo_i_din = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_real_spectrum_lo_i_din;

assign start_out = real_start;

assign twid_rom_M_imag_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_address0;

assign twid_rom_M_imag_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_imag_V_ce0;

assign twid_rom_M_real_V_address0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_address0;

assign twid_rom_M_real_V_ce0 = grp_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble_fu_60_twid_rom_M_real_V_ce0;

endmodule //hls_xfft2real_Loop_realfft_be_descramble_proc2
