// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_real2xfft_hls_real2xfft,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.150000,HLS_SYN_LAT=1549,HLS_SYN_TPT=512,HLS_SYN_MEM=10,HLS_SYN_DSP=0,HLS_SYN_FF=1589,HLS_SYN_LUT=1098,HLS_VERSION=2021_2}" *)

module hls_real2xfft (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst_n,
        din_TDATA,
        dout_TDATA,
        din_TVALID,
        din_TREADY,
        ap_start,
        dout_TVALID,
        dout_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst_n;
input  [15:0] din_TDATA;
output  [47:0] dout_TDATA;
input   din_TVALID;
output   din_TREADY;
input   ap_start;
output   dout_TVALID;
input   dout_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire   [15:0] data2window_V_i_q0;
wire   [15:0] data2window_V_t_q0;
wire   [15:0] data2window_V_2_i_q0;
wire   [15:0] data2window_V_2_t_q0;
wire   [15:0] windowed_V_i_q0;
wire   [15:0] windowed_V_t_q0;
wire   [15:0] windowed_V_1_i_q0;
wire   [15:0] windowed_V_1_t_q0;
wire    Loop_sliding_win_delay_proc1_U0_ap_start;
wire    Loop_sliding_win_delay_proc1_U0_ap_done;
wire    Loop_sliding_win_delay_proc1_U0_ap_continue;
wire    Loop_sliding_win_delay_proc1_U0_ap_idle;
wire    Loop_sliding_win_delay_proc1_U0_ap_ready;
wire   [15:0] Loop_sliding_win_delay_proc1_U0_nodelay_V_din;
wire    Loop_sliding_win_delay_proc1_U0_nodelay_V_write;
wire   [15:0] Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din;
wire    Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write;
wire   [15:0] Loop_sliding_win_delay_proc1_U0_delayed_V_din;
wire    Loop_sliding_win_delay_proc1_U0_delayed_V_write;
wire   [15:0] Loop_sliding_win_delay_proc1_U0_delayed_V_1_din;
wire    Loop_sliding_win_delay_proc1_U0_delayed_V_1_write;
wire    Loop_sliding_win_delay_proc1_U0_start_out;
wire    Loop_sliding_win_delay_proc1_U0_start_write;
wire    Loop_sliding_win_delay_proc1_U0_din_TREADY;
wire    Loop_sliding_win_output_proc2_U0_ap_start;
wire    Loop_sliding_win_output_proc2_U0_ap_done;
wire    Loop_sliding_win_output_proc2_U0_ap_continue;
wire    Loop_sliding_win_output_proc2_U0_ap_idle;
wire    Loop_sliding_win_output_proc2_U0_ap_ready;
wire    Loop_sliding_win_output_proc2_U0_delayed_V_read;
wire    Loop_sliding_win_output_proc2_U0_delayed_V_1_read;
wire    Loop_sliding_win_output_proc2_U0_nodelay_V_read;
wire    Loop_sliding_win_output_proc2_U0_nodelay_V_1_read;
wire   [8:0] Loop_sliding_win_output_proc2_U0_data2window_V_2_address0;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_2_we0;
wire   [15:0] Loop_sliding_win_output_proc2_U0_data2window_V_2_d0;
wire   [8:0] Loop_sliding_win_output_proc2_U0_data2window_V_address0;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_ce0;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_we0;
wire   [15:0] Loop_sliding_win_output_proc2_U0_data2window_V_d0;
wire    ap_channel_done_data2window_V;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_full_n;
reg    ap_sync_reg_channel_write_data2window_V;
wire    ap_sync_channel_write_data2window_V;
wire    ap_channel_done_data2window_V_2;
wire    Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n;
reg    ap_sync_reg_channel_write_data2window_V_2;
wire    ap_sync_channel_write_data2window_V_2;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0;
wire   [15:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0;
wire   [8:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0;
wire   [15:0] window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0;
wire    ap_channel_done_windowed_V_1;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n;
reg    ap_sync_reg_channel_write_windowed_V_1;
wire    ap_sync_channel_write_windowed_V_1;
wire    ap_channel_done_windowed_V;
wire    window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n;
reg    ap_sync_reg_channel_write_windowed_V;
wire    ap_sync_channel_write_windowed_V;
wire    Loop_real2xfft_output_proc3_U0_ap_start;
wire    Loop_real2xfft_output_proc3_U0_ap_done;
wire    Loop_real2xfft_output_proc3_U0_ap_continue;
wire    Loop_real2xfft_output_proc3_U0_ap_idle;
wire    Loop_real2xfft_output_proc3_U0_ap_ready;
wire   [8:0] Loop_real2xfft_output_proc3_U0_windowed_V_address0;
wire    Loop_real2xfft_output_proc3_U0_windowed_V_ce0;
wire   [8:0] Loop_real2xfft_output_proc3_U0_windowed_V_1_address0;
wire    Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0;
wire   [47:0] Loop_real2xfft_output_proc3_U0_dout_TDATA;
wire    Loop_real2xfft_output_proc3_U0_dout_TVALID;
wire    data2window_V_2_i_full_n;
wire    data2window_V_2_t_empty_n;
wire    data2window_V_i_full_n;
wire    data2window_V_t_empty_n;
wire    windowed_V_i_full_n;
wire    windowed_V_t_empty_n;
wire    windowed_V_1_i_full_n;
wire    windowed_V_1_t_empty_n;
wire    delayed_V_full_n;
wire   [15:0] delayed_V_dout;
wire    delayed_V_empty_n;
wire    nodelay_V_full_n;
wire   [15:0] nodelay_V_dout;
wire    nodelay_V_empty_n;
wire    nodelay_V_1_full_n;
wire   [15:0] nodelay_V_1_dout;
wire    nodelay_V_1_empty_n;
wire    delayed_V_1_full_n;
wire   [15:0] delayed_V_1_dout;
wire    delayed_V_1_empty_n;
wire   [0:0] start_for_Loop_sliding_win_output_proc2_U0_din;
wire    start_for_Loop_sliding_win_output_proc2_U0_full_n;
wire   [0:0] start_for_Loop_sliding_win_output_proc2_U0_dout;
wire    start_for_Loop_sliding_win_output_proc2_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_data2window_V = 1'b0;
#0 ap_sync_reg_channel_write_data2window_V_2 = 1'b0;
#0 ap_sync_reg_channel_write_windowed_V_1 = 1'b0;
#0 ap_sync_reg_channel_write_windowed_V = 1'b0;
end

hls_real2xfft_data2window_V_RAM_AUTO_2R1W #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
data2window_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_sliding_win_output_proc2_U0_data2window_V_address0),
    .i_ce0(Loop_sliding_win_output_proc2_U0_data2window_V_ce0),
    .i_we0(Loop_sliding_win_output_proc2_U0_data2window_V_we0),
    .i_d0(Loop_sliding_win_output_proc2_U0_data2window_V_d0),
    .i_q0(data2window_V_i_q0),
    .t_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0),
    .t_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(data2window_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(data2window_V_i_full_n),
    .i_write(ap_channel_done_data2window_V),
    .t_empty_n(data2window_V_t_empty_n),
    .t_read(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready)
);

hls_real2xfft_data2window_V_RAM_AUTO_2R1W #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
data2window_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_sliding_win_output_proc2_U0_data2window_V_2_address0),
    .i_ce0(Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0),
    .i_we0(Loop_sliding_win_output_proc2_U0_data2window_V_2_we0),
    .i_d0(Loop_sliding_win_output_proc2_U0_data2window_V_2_d0),
    .i_q0(data2window_V_2_i_q0),
    .t_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0),
    .t_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(data2window_V_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(data2window_V_2_i_full_n),
    .i_write(ap_channel_done_data2window_V_2),
    .t_empty_n(data2window_V_2_t_empty_n),
    .t_read(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready)
);

hls_real2xfft_data2window_V_RAM_AUTO_2R1W #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
windowed_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0),
    .i_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0),
    .i_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0),
    .i_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0),
    .i_q0(windowed_V_i_q0),
    .t_address0(Loop_real2xfft_output_proc3_U0_windowed_V_address0),
    .t_ce0(Loop_real2xfft_output_proc3_U0_windowed_V_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(windowed_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(windowed_V_i_full_n),
    .i_write(ap_channel_done_windowed_V),
    .t_empty_n(windowed_V_t_empty_n),
    .t_read(Loop_real2xfft_output_proc3_U0_ap_ready)
);

hls_real2xfft_data2window_V_RAM_AUTO_2R1W #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
windowed_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0),
    .i_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0),
    .i_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0),
    .i_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0),
    .i_q0(windowed_V_1_i_q0),
    .t_address0(Loop_real2xfft_output_proc3_U0_windowed_V_1_address0),
    .t_ce0(Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0),
    .t_we0(1'b0),
    .t_d0(16'd0),
    .t_q0(windowed_V_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(windowed_V_1_i_full_n),
    .i_write(ap_channel_done_windowed_V_1),
    .t_empty_n(windowed_V_1_t_empty_n),
    .t_read(Loop_real2xfft_output_proc3_U0_ap_ready)
);

hls_real2xfft_Loop_sliding_win_delay_proc1 Loop_sliding_win_delay_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_sliding_win_delay_proc1_U0_ap_start),
    .start_full_n(start_for_Loop_sliding_win_output_proc2_U0_full_n),
    .ap_done(Loop_sliding_win_delay_proc1_U0_ap_done),
    .ap_continue(Loop_sliding_win_delay_proc1_U0_ap_continue),
    .ap_idle(Loop_sliding_win_delay_proc1_U0_ap_idle),
    .ap_ready(Loop_sliding_win_delay_proc1_U0_ap_ready),
    .din_TVALID(din_TVALID),
    .nodelay_V_din(Loop_sliding_win_delay_proc1_U0_nodelay_V_din),
    .nodelay_V_full_n(nodelay_V_full_n),
    .nodelay_V_write(Loop_sliding_win_delay_proc1_U0_nodelay_V_write),
    .nodelay_V_1_din(Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din),
    .nodelay_V_1_full_n(nodelay_V_1_full_n),
    .nodelay_V_1_write(Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write),
    .delayed_V_din(Loop_sliding_win_delay_proc1_U0_delayed_V_din),
    .delayed_V_full_n(delayed_V_full_n),
    .delayed_V_write(Loop_sliding_win_delay_proc1_U0_delayed_V_write),
    .delayed_V_1_din(Loop_sliding_win_delay_proc1_U0_delayed_V_1_din),
    .delayed_V_1_full_n(delayed_V_1_full_n),
    .delayed_V_1_write(Loop_sliding_win_delay_proc1_U0_delayed_V_1_write),
    .start_out(Loop_sliding_win_delay_proc1_U0_start_out),
    .start_write(Loop_sliding_win_delay_proc1_U0_start_write),
    .din_TDATA(din_TDATA),
    .din_TREADY(Loop_sliding_win_delay_proc1_U0_din_TREADY)
);

hls_real2xfft_Loop_sliding_win_output_proc2 Loop_sliding_win_output_proc2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_sliding_win_output_proc2_U0_ap_start),
    .ap_done(Loop_sliding_win_output_proc2_U0_ap_done),
    .ap_continue(Loop_sliding_win_output_proc2_U0_ap_continue),
    .ap_idle(Loop_sliding_win_output_proc2_U0_ap_idle),
    .ap_ready(Loop_sliding_win_output_proc2_U0_ap_ready),
    .delayed_V_dout(delayed_V_dout),
    .delayed_V_empty_n(delayed_V_empty_n),
    .delayed_V_read(Loop_sliding_win_output_proc2_U0_delayed_V_read),
    .delayed_V_1_dout(delayed_V_1_dout),
    .delayed_V_1_empty_n(delayed_V_1_empty_n),
    .delayed_V_1_read(Loop_sliding_win_output_proc2_U0_delayed_V_1_read),
    .nodelay_V_dout(nodelay_V_dout),
    .nodelay_V_empty_n(nodelay_V_empty_n),
    .nodelay_V_read(Loop_sliding_win_output_proc2_U0_nodelay_V_read),
    .nodelay_V_1_dout(nodelay_V_1_dout),
    .nodelay_V_1_empty_n(nodelay_V_1_empty_n),
    .nodelay_V_1_read(Loop_sliding_win_output_proc2_U0_nodelay_V_1_read),
    .data2window_V_2_address0(Loop_sliding_win_output_proc2_U0_data2window_V_2_address0),
    .data2window_V_2_ce0(Loop_sliding_win_output_proc2_U0_data2window_V_2_ce0),
    .data2window_V_2_we0(Loop_sliding_win_output_proc2_U0_data2window_V_2_we0),
    .data2window_V_2_d0(Loop_sliding_win_output_proc2_U0_data2window_V_2_d0),
    .data2window_V_address0(Loop_sliding_win_output_proc2_U0_data2window_V_address0),
    .data2window_V_ce0(Loop_sliding_win_output_proc2_U0_data2window_V_ce0),
    .data2window_V_we0(Loop_sliding_win_output_proc2_U0_data2window_V_we0),
    .data2window_V_d0(Loop_sliding_win_output_proc2_U0_data2window_V_d0)
);

hls_real2xfft_window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_s window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start),
    .ap_done(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done),
    .ap_continue(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue),
    .ap_idle(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle),
    .ap_ready(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_ready),
    .indata_0_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_address0),
    .indata_0_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_0_ce0),
    .indata_0_q0(data2window_V_t_q0),
    .indata_1_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_address0),
    .indata_1_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_indata_1_ce0),
    .indata_1_q0(data2window_V_2_t_q0),
    .outdata_0_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_address0),
    .outdata_0_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_ce0),
    .outdata_0_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_we0),
    .outdata_0_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_d0),
    .outdata_1_address0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_address0),
    .outdata_1_ce0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_ce0),
    .outdata_1_we0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_we0),
    .outdata_1_d0(window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_d0)
);

hls_real2xfft_Loop_real2xfft_output_proc3 Loop_real2xfft_output_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_real2xfft_output_proc3_U0_ap_start),
    .ap_done(Loop_real2xfft_output_proc3_U0_ap_done),
    .ap_continue(Loop_real2xfft_output_proc3_U0_ap_continue),
    .ap_idle(Loop_real2xfft_output_proc3_U0_ap_idle),
    .ap_ready(Loop_real2xfft_output_proc3_U0_ap_ready),
    .dout_TREADY(dout_TREADY),
    .windowed_V_address0(Loop_real2xfft_output_proc3_U0_windowed_V_address0),
    .windowed_V_ce0(Loop_real2xfft_output_proc3_U0_windowed_V_ce0),
    .windowed_V_q0(windowed_V_t_q0),
    .windowed_V_1_address0(Loop_real2xfft_output_proc3_U0_windowed_V_1_address0),
    .windowed_V_1_ce0(Loop_real2xfft_output_proc3_U0_windowed_V_1_ce0),
    .windowed_V_1_q0(windowed_V_1_t_q0),
    .dout_TDATA(Loop_real2xfft_output_proc3_U0_dout_TDATA),
    .dout_TVALID(Loop_real2xfft_output_proc3_U0_dout_TVALID)
);

hls_real2xfft_fifo_w16_d256_A delayed_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_delay_proc1_U0_delayed_V_din),
    .if_full_n(delayed_V_full_n),
    .if_write(Loop_sliding_win_delay_proc1_U0_delayed_V_write),
    .if_dout(delayed_V_dout),
    .if_empty_n(delayed_V_empty_n),
    .if_read(Loop_sliding_win_output_proc2_U0_delayed_V_read)
);

hls_real2xfft_fifo_w16_d512_A nodelay_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_delay_proc1_U0_nodelay_V_din),
    .if_full_n(nodelay_V_full_n),
    .if_write(Loop_sliding_win_delay_proc1_U0_nodelay_V_write),
    .if_dout(nodelay_V_dout),
    .if_empty_n(nodelay_V_empty_n),
    .if_read(Loop_sliding_win_output_proc2_U0_nodelay_V_read)
);

hls_real2xfft_fifo_w16_d512_A nodelay_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_delay_proc1_U0_nodelay_V_1_din),
    .if_full_n(nodelay_V_1_full_n),
    .if_write(Loop_sliding_win_delay_proc1_U0_nodelay_V_1_write),
    .if_dout(nodelay_V_1_dout),
    .if_empty_n(nodelay_V_1_empty_n),
    .if_read(Loop_sliding_win_output_proc2_U0_nodelay_V_1_read)
);

hls_real2xfft_fifo_w16_d256_A delayed_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_sliding_win_delay_proc1_U0_delayed_V_1_din),
    .if_full_n(delayed_V_1_full_n),
    .if_write(Loop_sliding_win_delay_proc1_U0_delayed_V_1_write),
    .if_dout(delayed_V_1_dout),
    .if_empty_n(delayed_V_1_empty_n),
    .if_read(Loop_sliding_win_output_proc2_U0_delayed_V_1_read)
);

hls_real2xfft_start_for_Loop_sliding_win_output_proc2_U0 start_for_Loop_sliding_win_output_proc2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_sliding_win_output_proc2_U0_din),
    .if_full_n(start_for_Loop_sliding_win_output_proc2_U0_full_n),
    .if_write(Loop_sliding_win_delay_proc1_U0_start_write),
    .if_dout(start_for_Loop_sliding_win_output_proc2_U0_dout),
    .if_empty_n(start_for_Loop_sliding_win_output_proc2_U0_empty_n),
    .if_read(Loop_sliding_win_output_proc2_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_data2window_V <= 1'b0;
    end else begin
        if (((Loop_sliding_win_output_proc2_U0_ap_done & Loop_sliding_win_output_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_data2window_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_data2window_V <= ap_sync_channel_write_data2window_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_data2window_V_2 <= 1'b0;
    end else begin
        if (((Loop_sliding_win_output_proc2_U0_ap_done & Loop_sliding_win_output_proc2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_data2window_V_2 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_data2window_V_2 <= ap_sync_channel_write_data2window_V_2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_windowed_V <= 1'b0;
    end else begin
        if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_windowed_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_windowed_V <= ap_sync_channel_write_windowed_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_windowed_V_1 <= 1'b0;
    end else begin
        if (((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_windowed_V_1 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_windowed_V_1 <= ap_sync_channel_write_windowed_V_1;
        end
    end
end

assign Loop_real2xfft_output_proc3_U0_ap_continue = 1'b1;

assign Loop_real2xfft_output_proc3_U0_ap_start = (windowed_V_t_empty_n & windowed_V_1_t_empty_n);

assign Loop_sliding_win_delay_proc1_U0_ap_continue = 1'b1;

assign Loop_sliding_win_delay_proc1_U0_ap_start = ap_start;

assign Loop_sliding_win_output_proc2_U0_ap_continue = (ap_sync_channel_write_data2window_V_2 & ap_sync_channel_write_data2window_V);

assign Loop_sliding_win_output_proc2_U0_ap_start = start_for_Loop_sliding_win_output_proc2_U0_empty_n;

assign Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n = data2window_V_2_i_full_n;

assign Loop_sliding_win_output_proc2_U0_data2window_V_full_n = data2window_V_i_full_n;

assign ap_channel_done_data2window_V = ((ap_sync_reg_channel_write_data2window_V ^ 1'b1) & Loop_sliding_win_output_proc2_U0_ap_done);

assign ap_channel_done_data2window_V_2 = ((ap_sync_reg_channel_write_data2window_V_2 ^ 1'b1) & Loop_sliding_win_output_proc2_U0_ap_done);

assign ap_channel_done_windowed_V = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & (ap_sync_reg_channel_write_windowed_V ^ 1'b1));

assign ap_channel_done_windowed_V_1 = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_done & (ap_sync_reg_channel_write_windowed_V_1 ^ 1'b1));

assign ap_done = Loop_real2xfft_output_proc3_U0_ap_done;

assign ap_idle = (window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_idle & (windowed_V_1_t_empty_n ^ 1'b1) & (windowed_V_t_empty_n ^ 1'b1) & (data2window_V_t_empty_n ^ 1'b1) & (data2window_V_2_t_empty_n ^ 1'b1) & Loop_sliding_win_output_proc2_U0_ap_idle & Loop_sliding_win_delay_proc1_U0_ap_idle & Loop_real2xfft_output_proc3_U0_ap_idle);



assign ap_ready = Loop_sliding_win_delay_proc1_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_data2window_V = ((ap_channel_done_data2window_V & Loop_sliding_win_output_proc2_U0_data2window_V_full_n) | ap_sync_reg_channel_write_data2window_V);

assign ap_sync_channel_write_data2window_V_2 = ((ap_channel_done_data2window_V_2 & Loop_sliding_win_output_proc2_U0_data2window_V_2_full_n) | ap_sync_reg_channel_write_data2window_V_2);

assign ap_sync_channel_write_windowed_V = ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n & ap_channel_done_windowed_V) | ap_sync_reg_channel_write_windowed_V);

assign ap_sync_channel_write_windowed_V_1 = ((window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n & ap_channel_done_windowed_V_1) | ap_sync_reg_channel_write_windowed_V_1);

assign din_TREADY = Loop_sliding_win_delay_proc1_U0_din_TREADY;

assign dout_TDATA = Loop_real2xfft_output_proc3_U0_dout_TDATA;

assign dout_TVALID = Loop_real2xfft_output_proc3_U0_dout_TVALID;

assign start_for_Loop_sliding_win_output_proc2_U0_din = 1'b1;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_continue = (ap_sync_channel_write_windowed_V_1 & ap_sync_channel_write_windowed_V);

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_ap_start = (data2window_V_t_empty_n & data2window_V_2_t_empty_n);

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_0_full_n = windowed_V_i_full_n;

assign window_fn_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_3_0_ap_fixed_16_1_5_0_0_1024_2_2_U0_outdata_1_full_n = windowed_V_1_i_full_n;


reg find_df_deadlock = 0;
assign ap_local_deadlock = find_df_deadlock;
// synthesis translate_off
`include "hls_real2xfft_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
assign ap_local_block = find_kernel_block | find_df_deadlock;
// synthesis translate_off
`include "hls_real2xfft_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //hls_real2xfft

