// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_real2xfft_Loop_sliding_win_delay_proc1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        din_TVALID,
        nodelay_V_din,
        nodelay_V_full_n,
        nodelay_V_write,
        nodelay_V_1_din,
        nodelay_V_1_full_n,
        nodelay_V_1_write,
        delayed_V_din,
        delayed_V_full_n,
        delayed_V_write,
        delayed_V_1_din,
        delayed_V_1_full_n,
        delayed_V_1_write,
        start_out,
        start_write,
        din_TDATA,
        din_TREADY
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   din_TVALID;
output  [15:0] nodelay_V_din;
input   nodelay_V_full_n;
output   nodelay_V_write;
output  [15:0] nodelay_V_1_din;
input   nodelay_V_1_full_n;
output   nodelay_V_1_write;
output  [15:0] delayed_V_din;
input   delayed_V_full_n;
output   delayed_V_write;
output  [15:0] delayed_V_1_din;
input   delayed_V_1_full_n;
output   delayed_V_1_write;
output   start_out;
output   start_write;
input  [15:0] din_TDATA;
output   din_TREADY;

reg ap_done;
reg ap_idle;
reg nodelay_V_write;
reg nodelay_V_1_write;
reg delayed_V_write;
reg delayed_V_1_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
wire   [0:0] icmp_ln75_fu_122_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_block_state2_pp0_stage0_iter0;
reg   [0:0] trunc_ln78_reg_136;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    delay_line_Array_ce0;
reg    delay_line_Array_we0;
wire   [15:0] delay_line_Array_q0;
reg    delayed_V_blk_n;
wire    ap_block_pp0_stage0;
reg    nodelay_V_blk_n;
reg    din_TDATA_blk_n;
reg    nodelay_V_1_blk_n;
reg    delayed_V_1_blk_n;
reg   [8:0] i3_reg_88;
reg   [15:0] din_val_reg_130;
wire   [0:0] trunc_ln78_fu_102_p1;
wire   [8:0] i_fu_106_p2;
reg   [8:0] i_reg_140;
reg   [15:0] p_0_reg_145;
reg   [0:0] icmp_ln75_reg_151;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg   [8:0] ap_phi_mux_i3_phi_fu_92_p6;
reg    ap_block_pp0_stage0_01001;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_din_U_apdone_blk;
wire   [15:0] din_TDATA_int_regslice;
wire    din_TVALID_int_regslice;
reg    din_TREADY_int_regslice;
wire    regslice_both_din_U_ack_in;
reg    ap_condition_113;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

hls_real2xfft_Loop_sliding_win_delay_proc1_delay_line_Array_SHIFTREG_AUTO_0R0W #(
    .DataWidth( 16 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
delay_line_Array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(9'd511),
    .ce0(delay_line_Array_ce0),
    .we0(delay_line_Array_we0),
    .d0(din_TDATA_int_regslice),
    .q0(delay_line_Array_q0)
);

hls_real2xfft_regslice_both #(
    .DataWidth( 16 ))
regslice_both_din_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_TDATA),
    .vld_in(din_TVALID),
    .ack_in(regslice_both_din_U_ack_in),
    .data_out(din_TDATA_int_regslice),
    .vld_out(din_TVALID_int_regslice),
    .ack_out(din_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_151 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= real_start;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_151 == 1'd0))) begin
        i3_reg_88 <= i_reg_140;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_151 == 1'd1)) | (~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        i3_reg_88 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_val_reg_130 <= din_TDATA_int_regslice;
        icmp_ln75_reg_151 <= icmp_ln75_fu_122_p2;
        p_0_reg_145 <= delay_line_Array_q0;
        trunc_ln78_reg_136 <= trunc_ln78_fu_102_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_140 <= i_fu_106_p2;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln75_reg_151 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_113)) begin
        if ((icmp_ln75_reg_151 == 1'd1)) begin
            ap_phi_mux_i3_phi_fu_92_p6 = 9'd0;
        end else if ((icmp_ln75_reg_151 == 1'd0)) begin
            ap_phi_mux_i3_phi_fu_92_p6 = i_reg_140;
        end else begin
            ap_phi_mux_i3_phi_fu_92_p6 = i3_reg_88;
        end
    end else begin
        ap_phi_mux_i3_phi_fu_92_p6 = i3_reg_88;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delay_line_Array_ce0 = 1'd1;
    end else begin
        delay_line_Array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delay_line_Array_we0 = 1'd1;
    end else begin
        delay_line_Array_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delayed_V_1_blk_n = delayed_V_1_full_n;
    end else begin
        delayed_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delayed_V_1_write = 1'b1;
    end else begin
        delayed_V_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delayed_V_blk_n = delayed_V_full_n;
    end else begin
        delayed_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        delayed_V_write = 1'b1;
    end else begin
        delayed_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_TDATA_blk_n = din_TVALID_int_regslice;
    end else begin
        din_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        din_TREADY_int_regslice = 1'b1;
    end else begin
        din_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (icmp_ln75_fu_122_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodelay_V_1_blk_n = nodelay_V_1_full_n;
    end else begin
        nodelay_V_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodelay_V_1_write = 1'b1;
    end else begin
        nodelay_V_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodelay_V_blk_n = nodelay_V_full_n;
    end else begin
        nodelay_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (trunc_ln78_reg_136 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nodelay_V_write = 1'b1;
    end else begin
        nodelay_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((delayed_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((delayed_V_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd0)) | ((nodelay_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((trunc_ln78_reg_136 == 1'd0) & (nodelay_V_full_n == 1'b0)))) | ((real_start == 1'b1) & (din_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((delayed_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((delayed_V_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd0)) | ((nodelay_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((trunc_ln78_reg_136 == 1'd0) & (nodelay_V_full_n == 1'b0)))) | ((real_start == 1'b1) & (din_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((delayed_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((delayed_V_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd0)) | ((nodelay_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((trunc_ln78_reg_136 == 1'd0) & (nodelay_V_full_n == 1'b0)))) | ((real_start == 1'b1) & (din_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (din_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((delayed_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((delayed_V_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd0)) | ((nodelay_V_1_full_n == 1'b0) & (trunc_ln78_reg_136 == 1'd1)) | ((trunc_ln78_reg_136 == 1'd0) & (nodelay_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_113 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = real_start;

assign ap_ready = internal_ap_ready;

assign delayed_V_1_din = p_0_reg_145;

assign delayed_V_din = p_0_reg_145;

assign din_TREADY = regslice_both_din_U_ack_in;

assign i_fu_106_p2 = (ap_phi_mux_i3_phi_fu_92_p6 + 9'd1);

assign icmp_ln75_fu_122_p2 = ((ap_phi_mux_i3_phi_fu_92_p6 == 9'd511) ? 1'b1 : 1'b0);

assign nodelay_V_1_din = din_val_reg_130;

assign nodelay_V_din = din_val_reg_130;

assign start_out = real_start;

assign trunc_ln78_fu_102_p1 = ap_phi_mux_i3_phi_fu_92_p6[0:0];

endmodule //hls_real2xfft_Loop_sliding_win_delay_proc1
