// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_xfft2real_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        real_spectrum_lo_i_din,
        real_spectrum_lo_i_full_n,
        real_spectrum_lo_i_write,
        descramble_buf_M_real_V_address0,
        descramble_buf_M_real_V_ce0,
        descramble_buf_M_real_V_q0,
        descramble_buf_M_imag_V_address0,
        descramble_buf_M_imag_V_ce0,
        descramble_buf_M_imag_V_q0,
        descramble_buf_M_imag_V_1_address0,
        descramble_buf_M_imag_V_1_ce0,
        descramble_buf_M_imag_V_1_q0,
        descramble_buf_M_real_V_1_address0,
        descramble_buf_M_real_V_1_ce0,
        descramble_buf_M_real_V_1_q0,
        twid_rom_M_real_V_address0,
        twid_rom_M_real_V_ce0,
        twid_rom_M_real_V_q0,
        twid_rom_M_imag_V_address0,
        twid_rom_M_imag_V_ce0,
        twid_rom_M_imag_V_q0,
        descramble_buf_M_imag_V_1_load,
        descramble_buf_M_real_V_1_load,
        real_spectrum_hi_buf_M_real_V_address0,
        real_spectrum_hi_buf_M_real_V_ce0,
        real_spectrum_hi_buf_M_real_V_we0,
        real_spectrum_hi_buf_M_real_V_d0,
        real_spectrum_hi_buf_M_imag_V_address0,
        real_spectrum_hi_buf_M_imag_V_ce0,
        real_spectrum_hi_buf_M_imag_V_we0,
        real_spectrum_hi_buf_M_imag_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] real_spectrum_lo_i_din;
input   real_spectrum_lo_i_full_n;
output   real_spectrum_lo_i_write;
output  [7:0] descramble_buf_M_real_V_address0;
output   descramble_buf_M_real_V_ce0;
input  [15:0] descramble_buf_M_real_V_q0;
output  [7:0] descramble_buf_M_imag_V_address0;
output   descramble_buf_M_imag_V_ce0;
input  [15:0] descramble_buf_M_imag_V_q0;
output  [7:0] descramble_buf_M_imag_V_1_address0;
output   descramble_buf_M_imag_V_1_ce0;
input  [15:0] descramble_buf_M_imag_V_1_q0;
output  [7:0] descramble_buf_M_real_V_1_address0;
output   descramble_buf_M_real_V_1_ce0;
input  [15:0] descramble_buf_M_real_V_1_q0;
output  [7:0] twid_rom_M_real_V_address0;
output   twid_rom_M_real_V_ce0;
input  [14:0] twid_rom_M_real_V_q0;
output  [7:0] twid_rom_M_imag_V_address0;
output   twid_rom_M_imag_V_ce0;
input  [15:0] twid_rom_M_imag_V_q0;
input  [15:0] descramble_buf_M_imag_V_1_load;
input  [15:0] descramble_buf_M_real_V_1_load;
output  [7:0] real_spectrum_hi_buf_M_real_V_address0;
output   real_spectrum_hi_buf_M_real_V_ce0;
output   real_spectrum_hi_buf_M_real_V_we0;
output  [15:0] real_spectrum_hi_buf_M_real_V_d0;
output  [7:0] real_spectrum_hi_buf_M_imag_V_address0;
output   real_spectrum_hi_buf_M_imag_V_ce0;
output   real_spectrum_hi_buf_M_imag_V_we0;
output  [15:0] real_spectrum_hi_buf_M_imag_V_d0;

reg ap_idle;
reg real_spectrum_lo_i_write;
reg descramble_buf_M_real_V_ce0;
reg descramble_buf_M_imag_V_ce0;
reg descramble_buf_M_imag_V_1_ce0;
reg descramble_buf_M_real_V_1_ce0;
reg twid_rom_M_real_V_ce0;
reg twid_rom_M_imag_V_ce0;
reg real_spectrum_hi_buf_M_real_V_ce0;
reg real_spectrum_hi_buf_M_real_V_we0;
reg real_spectrum_hi_buf_M_imag_V_ce0;
reg real_spectrum_hi_buf_M_imag_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
reg    ap_block_state17_pp0_stage0_iter16;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln88_fu_215_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    real_spectrum_lo_i_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [8:0] i_2_reg_814;
reg   [8:0] i_2_reg_814_pp0_iter1_reg;
reg   [8:0] i_2_reg_814_pp0_iter2_reg;
reg   [8:0] i_2_reg_814_pp0_iter3_reg;
wire   [8:0] add_ln88_fu_221_p2;
reg   [8:0] add_ln88_reg_824;
wire   [7:0] trunc_ln88_fu_227_p1;
reg   [7:0] trunc_ln88_reg_829;
reg   [7:0] trunc_ln88_reg_829_pp0_iter1_reg;
wire   [7:0] sub_ln712_4_fu_231_p2;
reg   [7:0] sub_ln712_4_reg_834;
wire   [63:0] zext_ln712_fu_237_p1;
reg   [63:0] zext_ln712_reg_839;
reg   [63:0] zext_ln712_reg_839_pp0_iter2_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter3_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter4_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter5_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter6_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter7_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter8_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter9_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter10_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter11_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter12_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter13_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter14_reg;
reg   [63:0] zext_ln712_reg_839_pp0_iter15_reg;
wire   [63:0] zext_ln90_fu_245_p1;
reg   [63:0] zext_ln90_reg_851;
reg   [15:0] descramble_buf_M_imag_V_1_load_1_reg_866;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter5_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter6_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter7_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter8_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter9_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter10_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter11_reg;
reg  signed [15:0] descramble_buf_M_imag_V_load_reg_876_pp0_iter12_reg;
wire   [0:0] icmp_ln92_fu_254_p2;
reg   [0:0] icmp_ln92_reg_883;
reg   [0:0] icmp_ln92_reg_883_pp0_iter5_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter6_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter7_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter8_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter9_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter10_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter11_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter12_reg;
reg   [0:0] icmp_ln92_reg_883_pp0_iter13_reg;
wire   [15:0] sub_ln712_1_fu_259_p2;
reg   [15:0] sub_ln712_1_reg_891;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter6_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter7_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter8_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter9_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter10_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter11_reg;
reg  signed [15:0] descramble_buf_M_real_V_load_reg_906_pp0_iter12_reg;
reg   [15:0] descramble_buf_M_real_V_1_load_1_reg_913;
wire   [16:0] ret_V_8_fu_270_p2;
reg   [16:0] ret_V_8_reg_918;
wire   [16:0] ret_V_7_fu_276_p2;
reg   [16:0] ret_V_7_reg_923;
reg   [0:0] tmp_2_reg_928;
reg   [0:0] tmp_2_reg_928_pp0_iter6_reg;
reg   [15:0] trunc_ln1201_5_reg_933;
reg   [15:0] trunc_ln1201_5_reg_933_pp0_iter6_reg;
reg   [15:0] trunc_ln1201_7_reg_938;
wire   [16:0] ret_V_9_fu_316_p2;
reg   [16:0] ret_V_9_reg_943;
wire   [16:0] ret_V_6_fu_322_p2;
reg   [16:0] ret_V_6_reg_948;
reg   [0:0] tmp_reg_953;
reg   [0:0] tmp_reg_953_pp0_iter7_reg;
reg   [15:0] trunc_ln1201_2_reg_958;
reg   [15:0] trunc_ln1201_2_reg_958_pp0_iter7_reg;
reg   [15:0] trunc_ln1201_4_reg_963;
wire   [15:0] g_M_real_V_fu_389_p3;
reg   [15:0] g_M_real_V_reg_968;
reg   [0:0] tmp_4_reg_973;
reg   [0:0] tmp_4_reg_973_pp0_iter7_reg;
reg   [15:0] trunc_ln1201_3_reg_978;
reg   [15:0] trunc_ln1201_3_reg_978_pp0_iter7_reg;
reg   [14:0] w_M_real_V_reg_983;
reg  signed [15:0] w_M_imag_V_reg_988;
reg   [15:0] trunc_ln1201_1_reg_993;
wire   [15:0] f_M_imag_V_fu_435_p3;
reg   [15:0] f_M_imag_V_reg_998;
reg   [15:0] f_M_imag_V_reg_998_pp0_iter8_reg;
reg   [15:0] f_M_imag_V_reg_998_pp0_iter9_reg;
reg   [15:0] f_M_imag_V_reg_998_pp0_iter10_reg;
reg   [15:0] f_M_imag_V_reg_998_pp0_iter11_reg;
reg   [15:0] f_M_imag_V_reg_998_pp0_iter12_reg;
wire  signed [30:0] sext_ln1171_fu_441_p1;
reg   [15:0] trunc_ln1201_s_reg_1010;
wire   [30:0] zext_ln1168_fu_459_p1;
reg   [30:0] zext_ln1168_reg_1015;
reg   [30:0] zext_ln1168_reg_1015_pp0_iter8_reg;
wire  signed [30:0] sext_ln1171_2_fu_462_p1;
reg  signed [30:0] sext_ln1171_2_reg_1021;
reg  signed [30:0] sext_ln1171_2_reg_1021_pp0_iter8_reg;
wire   [15:0] f_M_real_V_fu_470_p3;
reg   [15:0] f_M_real_V_reg_1027;
reg   [15:0] f_M_real_V_reg_1027_pp0_iter9_reg;
reg   [15:0] f_M_real_V_reg_1027_pp0_iter10_reg;
reg   [15:0] f_M_real_V_reg_1027_pp0_iter11_reg;
reg   [15:0] f_M_real_V_reg_1027_pp0_iter12_reg;
wire   [15:0] g_M_imag_V_fu_481_p3;
reg   [15:0] g_M_imag_V_reg_1033;
wire  signed [30:0] sext_ln1171_1_fu_487_p1;
wire  signed [30:0] grp_fu_771_p2;
reg  signed [30:0] r_V_2_reg_1044;
wire  signed [30:0] grp_fu_777_p2;
reg  signed [30:0] mul_ln1245_reg_1049;
reg   [15:0] p_r_V_reg_1054;
reg   [15:0] trunc_ln2_reg_1060;
wire   [15:0] add_ln712_fu_508_p2;
reg   [15:0] add_ln712_reg_1066;
wire   [15:0] sub_ln712_fu_512_p2;
reg   [15:0] sub_ln712_reg_1071;
wire   [15:0] sub_ln712_2_fu_516_p2;
reg   [15:0] sub_ln712_2_reg_1076;
wire   [15:0] p_r_M_real_V_1_fu_520_p2;
reg   [15:0] p_r_M_real_V_1_reg_1081;
wire   [15:0] sub_ln712_3_fu_524_p2;
reg   [15:0] sub_ln712_3_reg_1086;
wire   [15:0] p_r_M_imag_V_1_fu_528_p2;
reg   [15:0] p_r_M_imag_V_1_reg_1091;
reg   [0:0] tmp_5_reg_1096;
reg   [15:0] trunc_ln1201_6_reg_1101;
reg   [14:0] trunc_ln1201_9_reg_1106;
reg   [0:0] tmp_6_reg_1111;
reg   [15:0] trunc_ln1201_10_reg_1116;
reg   [14:0] trunc_ln1201_11_reg_1121;
reg   [0:0] tmp_7_reg_1126;
reg   [15:0] trunc_ln1201_12_reg_1131;
reg   [14:0] trunc_ln1201_13_reg_1136;
reg   [0:0] tmp_8_reg_1141;
reg   [15:0] trunc_ln1201_14_reg_1146;
reg   [14:0] trunc_ln1201_15_reg_1151;
wire   [15:0] select_ln1201_fu_712_p3;
reg   [15:0] select_ln1201_reg_1156;
wire   [15:0] select_ln1201_3_fu_727_p3;
reg   [15:0] select_ln1201_3_reg_1161;
wire   [15:0] select_ln1201_4_fu_742_p3;
reg   [15:0] select_ln1201_4_reg_1166;
wire   [15:0] select_ln1201_5_fu_757_p3;
reg   [15:0] select_ln1201_5_reg_1171;
wire   [63:0] zext_ln88_fu_249_p1;
reg   [8:0] i_fu_80;
reg   [8:0] ap_sig_allocacmp_i_2;
wire    ap_loop_init;
reg    ap_block_pp0_stage0_01001;
wire  signed [16:0] sext_ln1245_3_fu_264_p1;
wire  signed [16:0] sext_ln1245_2_fu_267_p1;
wire  signed [16:0] sext_ln1245_1_fu_310_p1;
wire  signed [16:0] sext_ln1245_fu_313_p1;
wire   [16:0] sub_ln1201_2_fu_346_p2;
wire   [16:0] r_V_5_fu_361_p2;
wire   [0:0] tmp_3_fu_366_p3;
wire   [15:0] sub_ln1201_4_fu_374_p2;
wire   [15:0] trunc_ln1201_8_fu_379_p4;
wire   [16:0] sub_ln1201_fu_415_p2;
wire   [15:0] sub_ln1201_3_fu_430_p2;
wire   [16:0] sub_ln1201_5_fu_444_p2;
wire   [15:0] sub_ln1201_1_fu_465_p2;
wire   [15:0] sub_ln1201_6_fu_476_p2;
wire  signed [30:0] grp_fu_790_p3;
wire  signed [30:0] grp_fu_783_p3;
wire  signed [15:0] t_V_7_fu_532_p3;
wire  signed [15:0] t_V_6_fu_537_p3;
wire  signed [15:0] t_V_5_fu_542_p3;
wire  signed [15:0] t_V_4_fu_547_p3;
wire  signed [16:0] sext_ln1201_fu_564_p1;
wire   [16:0] sub_ln1201_7_fu_576_p2;
wire  signed [16:0] sext_ln1201_2_fu_560_p1;
wire   [16:0] sub_ln1201_9_fu_610_p2;
wire  signed [16:0] sext_ln1201_4_fu_556_p1;
wire   [16:0] sub_ln1201_11_fu_644_p2;
wire  signed [16:0] sext_ln1201_6_fu_552_p1;
wire   [16:0] sub_ln1201_13_fu_678_p2;
wire   [15:0] sub_ln1201_8_fu_707_p2;
wire  signed [15:0] sext_ln1201_1_fu_704_p1;
wire   [15:0] sub_ln1201_10_fu_722_p2;
wire  signed [15:0] sext_ln1201_3_fu_719_p1;
wire   [15:0] sub_ln1201_12_fu_737_p2;
wire  signed [15:0] sext_ln1201_5_fu_734_p1;
wire   [15:0] sub_ln1201_14_fu_752_p2;
wire  signed [15:0] sext_ln1201_7_fu_749_p1;
wire  signed [15:0] grp_fu_771_p0;
wire   [14:0] grp_fu_771_p1;
wire  signed [15:0] grp_fu_777_p1;
wire  signed [15:0] grp_fu_783_p0;
wire   [14:0] grp_fu_783_p1;
wire  signed [15:0] grp_fu_790_p0;
wire  signed [15:0] grp_fu_790_p1;
reg    grp_fu_771_ce;
reg    grp_fu_777_ce;
reg    grp_fu_783_ce;
reg    grp_fu_790_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [30:0] grp_fu_771_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_done_reg = 1'b0;
end

hls_xfft2real_mul_mul_16s_15ns_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 31 ))
mul_mul_16s_15ns_31_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_771_p0),
    .din1(grp_fu_771_p1),
    .ce(grp_fu_771_ce),
    .dout(grp_fu_771_p2)
);

hls_xfft2real_mul_mul_16s_16s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 31 ))
mul_mul_16s_16s_31_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(w_M_imag_V_reg_988),
    .din1(grp_fu_777_p1),
    .ce(grp_fu_777_ce),
    .dout(grp_fu_777_p2)
);

hls_xfft2real_mac_muladd_16s_15ns_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_16s_15ns_31s_31_4_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_783_p0),
    .din1(grp_fu_783_p1),
    .din2(mul_ln1245_reg_1049),
    .ce(grp_fu_783_ce),
    .dout(grp_fu_783_p3)
);

hls_xfft2real_mac_mulsub_16s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_mulsub_16s_16s_31s_31_4_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_790_p0),
    .din1(grp_fu_790_p1),
    .din2(r_V_2_reg_1044),
    .ce(grp_fu_790_ce),
    .dout(grp_fu_790_p3)
);

hls_xfft2real_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_80 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_80 <= add_ln88_reg_824;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln92_reg_883_pp0_iter12_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln712_reg_1066 <= add_ln712_fu_508_p2;
        sub_ln712_reg_1071 <= sub_ln712_fu_512_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln88_reg_824 <= add_ln88_fu_221_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        i_2_reg_814 <= ap_sig_allocacmp_i_2;
        i_2_reg_814_pp0_iter1_reg <= i_2_reg_814;
        trunc_ln88_reg_829_pp0_iter1_reg <= trunc_ln88_reg_829;
        zext_ln712_reg_839[7 : 0] <= zext_ln712_fu_237_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        descramble_buf_M_imag_V_1_load_1_reg_866 <= descramble_buf_M_imag_V_1_q0;
        descramble_buf_M_imag_V_load_reg_876 <= descramble_buf_M_imag_V_q0;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter10_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter9_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter11_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter10_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter12_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter11_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter5_reg <= descramble_buf_M_imag_V_load_reg_876;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter6_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter5_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter7_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter6_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter8_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter7_reg;
        descramble_buf_M_imag_V_load_reg_876_pp0_iter9_reg <= descramble_buf_M_imag_V_load_reg_876_pp0_iter8_reg;
        descramble_buf_M_real_V_1_load_1_reg_913 <= descramble_buf_M_real_V_1_q0;
        descramble_buf_M_real_V_load_reg_906 <= descramble_buf_M_real_V_q0;
        descramble_buf_M_real_V_load_reg_906_pp0_iter10_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter9_reg;
        descramble_buf_M_real_V_load_reg_906_pp0_iter11_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter10_reg;
        descramble_buf_M_real_V_load_reg_906_pp0_iter12_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter11_reg;
        descramble_buf_M_real_V_load_reg_906_pp0_iter6_reg <= descramble_buf_M_real_V_load_reg_906;
        descramble_buf_M_real_V_load_reg_906_pp0_iter7_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter6_reg;
        descramble_buf_M_real_V_load_reg_906_pp0_iter8_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter7_reg;
        descramble_buf_M_real_V_load_reg_906_pp0_iter9_reg <= descramble_buf_M_real_V_load_reg_906_pp0_iter8_reg;
        f_M_imag_V_reg_998 <= f_M_imag_V_fu_435_p3;
        f_M_imag_V_reg_998_pp0_iter10_reg <= f_M_imag_V_reg_998_pp0_iter9_reg;
        f_M_imag_V_reg_998_pp0_iter11_reg <= f_M_imag_V_reg_998_pp0_iter10_reg;
        f_M_imag_V_reg_998_pp0_iter12_reg <= f_M_imag_V_reg_998_pp0_iter11_reg;
        f_M_imag_V_reg_998_pp0_iter8_reg <= f_M_imag_V_reg_998;
        f_M_imag_V_reg_998_pp0_iter9_reg <= f_M_imag_V_reg_998_pp0_iter8_reg;
        f_M_real_V_reg_1027 <= f_M_real_V_fu_470_p3;
        f_M_real_V_reg_1027_pp0_iter10_reg <= f_M_real_V_reg_1027_pp0_iter9_reg;
        f_M_real_V_reg_1027_pp0_iter11_reg <= f_M_real_V_reg_1027_pp0_iter10_reg;
        f_M_real_V_reg_1027_pp0_iter12_reg <= f_M_real_V_reg_1027_pp0_iter11_reg;
        f_M_real_V_reg_1027_pp0_iter9_reg <= f_M_real_V_reg_1027;
        g_M_imag_V_reg_1033 <= g_M_imag_V_fu_481_p3;
        g_M_real_V_reg_968 <= g_M_real_V_fu_389_p3;
        i_2_reg_814_pp0_iter2_reg <= i_2_reg_814_pp0_iter1_reg;
        i_2_reg_814_pp0_iter3_reg <= i_2_reg_814_pp0_iter2_reg;
        icmp_ln92_reg_883 <= icmp_ln92_fu_254_p2;
        icmp_ln92_reg_883_pp0_iter10_reg <= icmp_ln92_reg_883_pp0_iter9_reg;
        icmp_ln92_reg_883_pp0_iter11_reg <= icmp_ln92_reg_883_pp0_iter10_reg;
        icmp_ln92_reg_883_pp0_iter12_reg <= icmp_ln92_reg_883_pp0_iter11_reg;
        icmp_ln92_reg_883_pp0_iter13_reg <= icmp_ln92_reg_883_pp0_iter12_reg;
        icmp_ln92_reg_883_pp0_iter5_reg <= icmp_ln92_reg_883;
        icmp_ln92_reg_883_pp0_iter6_reg <= icmp_ln92_reg_883_pp0_iter5_reg;
        icmp_ln92_reg_883_pp0_iter7_reg <= icmp_ln92_reg_883_pp0_iter6_reg;
        icmp_ln92_reg_883_pp0_iter8_reg <= icmp_ln92_reg_883_pp0_iter7_reg;
        icmp_ln92_reg_883_pp0_iter9_reg <= icmp_ln92_reg_883_pp0_iter8_reg;
        mul_ln1245_reg_1049 <= grp_fu_777_p2;
        p_r_V_reg_1054 <= {{grp_fu_790_p3[30:15]}};
        r_V_2_reg_1044 <= grp_fu_771_p2;
        ret_V_6_reg_948 <= ret_V_6_fu_322_p2;
        ret_V_7_reg_923 <= ret_V_7_fu_276_p2;
        ret_V_8_reg_918 <= ret_V_8_fu_270_p2;
        ret_V_9_reg_943 <= ret_V_9_fu_316_p2;
        select_ln1201_3_reg_1161 <= select_ln1201_3_fu_727_p3;
        select_ln1201_4_reg_1166 <= select_ln1201_4_fu_742_p3;
        select_ln1201_5_reg_1171 <= select_ln1201_5_fu_757_p3;
        select_ln1201_reg_1156 <= select_ln1201_fu_712_p3;
        sext_ln1171_2_reg_1021 <= sext_ln1171_2_fu_462_p1;
        sext_ln1171_2_reg_1021_pp0_iter8_reg <= sext_ln1171_2_reg_1021;
        sub_ln712_1_reg_891 <= sub_ln712_1_fu_259_p2;
        tmp_2_reg_928 <= ret_V_7_fu_276_p2[32'd16];
        tmp_2_reg_928_pp0_iter6_reg <= tmp_2_reg_928;
        tmp_4_reg_973 <= ret_V_9_fu_316_p2[32'd16];
        tmp_4_reg_973_pp0_iter7_reg <= tmp_4_reg_973;
        tmp_5_reg_1096 <= t_V_4_fu_547_p3[32'd15];
        tmp_6_reg_1111 <= t_V_5_fu_542_p3[32'd15];
        tmp_7_reg_1126 <= t_V_6_fu_537_p3[32'd15];
        tmp_8_reg_1141 <= t_V_7_fu_532_p3[32'd15];
        tmp_reg_953 <= ret_V_6_fu_322_p2[32'd16];
        tmp_reg_953_pp0_iter7_reg <= tmp_reg_953;
        trunc_ln1201_10_reg_1116 <= {{sub_ln1201_9_fu_610_p2[16:1]}};
        trunc_ln1201_11_reg_1121 <= {{t_V_5_fu_542_p3[15:1]}};
        trunc_ln1201_12_reg_1131 <= {{sub_ln1201_11_fu_644_p2[16:1]}};
        trunc_ln1201_13_reg_1136 <= {{t_V_6_fu_537_p3[15:1]}};
        trunc_ln1201_14_reg_1146 <= {{sub_ln1201_13_fu_678_p2[16:1]}};
        trunc_ln1201_15_reg_1151 <= {{t_V_7_fu_532_p3[15:1]}};
        trunc_ln1201_2_reg_958 <= {{ret_V_6_fu_322_p2[16:1]}};
        trunc_ln1201_2_reg_958_pp0_iter7_reg <= trunc_ln1201_2_reg_958;
        trunc_ln1201_3_reg_978 <= {{ret_V_9_fu_316_p2[16:1]}};
        trunc_ln1201_3_reg_978_pp0_iter7_reg <= trunc_ln1201_3_reg_978;
        trunc_ln1201_5_reg_933 <= {{ret_V_7_fu_276_p2[16:1]}};
        trunc_ln1201_5_reg_933_pp0_iter6_reg <= trunc_ln1201_5_reg_933;
        trunc_ln1201_6_reg_1101 <= {{sub_ln1201_7_fu_576_p2[16:1]}};
        trunc_ln1201_7_reg_938 <= {{ret_V_8_fu_270_p2[16:1]}};
        trunc_ln1201_9_reg_1106 <= {{t_V_4_fu_547_p3[15:1]}};
        trunc_ln2_reg_1060 <= {{grp_fu_783_p3[30:15]}};
        w_M_imag_V_reg_988 <= twid_rom_M_imag_V_q0;
        w_M_real_V_reg_983 <= twid_rom_M_real_V_q0;
        zext_ln1168_reg_1015[14 : 0] <= zext_ln1168_fu_459_p1[14 : 0];
        zext_ln1168_reg_1015_pp0_iter8_reg[14 : 0] <= zext_ln1168_reg_1015[14 : 0];
        zext_ln712_reg_839_pp0_iter10_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter9_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter11_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter10_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter12_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter11_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter13_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter12_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter14_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter13_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter15_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter14_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter2_reg[7 : 0] <= zext_ln712_reg_839[7 : 0];
        zext_ln712_reg_839_pp0_iter3_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter2_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter4_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter3_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter5_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter4_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter6_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter5_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter7_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter6_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter8_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter7_reg[7 : 0];
        zext_ln712_reg_839_pp0_iter9_reg[7 : 0] <= zext_ln712_reg_839_pp0_iter8_reg[7 : 0];
        zext_ln90_reg_851[7 : 0] <= zext_ln90_fu_245_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln92_reg_883_pp0_iter12_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_r_M_imag_V_1_reg_1091 <= p_r_M_imag_V_1_fu_528_p2;
        p_r_M_real_V_1_reg_1081 <= p_r_M_real_V_1_fu_520_p2;
        sub_ln712_2_reg_1076 <= sub_ln712_2_fu_516_p2;
        sub_ln712_3_reg_1086 <= sub_ln712_3_fu_524_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln88_fu_215_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sub_ln712_4_reg_834 <= sub_ln712_4_fu_231_p2;
        trunc_ln88_reg_829 <= trunc_ln88_fu_227_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_953 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln1201_1_reg_993 <= {{sub_ln1201_fu_415_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_928 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln1201_4_reg_963 <= {{sub_ln1201_2_fu_346_p2[16:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_reg_973 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        trunc_ln1201_s_reg_1010 <= {{sub_ln1201_5_fu_444_p2[16:1]}};
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln88_fu_215_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter15_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_i_2 = 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_i_2 = add_ln88_reg_824;
        end else begin
            ap_sig_allocacmp_i_2 = i_fu_80;
        end
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_80;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        descramble_buf_M_imag_V_1_ce0 = 1'b1;
    end else begin
        descramble_buf_M_imag_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        descramble_buf_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        descramble_buf_M_real_V_1_ce0 = 1'b1;
    end else begin
        descramble_buf_M_real_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        descramble_buf_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_771_ce = 1'b1;
    end else begin
        grp_fu_771_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_777_ce = 1'b1;
    end else begin
        grp_fu_777_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_783_ce = 1'b1;
    end else begin
        grp_fu_783_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_790_ce = 1'b1;
    end else begin
        grp_fu_790_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_M_imag_V_ce0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_M_imag_V_we0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_M_real_V_ce0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_hi_buf_M_real_V_we0 = 1'b1;
    end else begin
        real_spectrum_hi_buf_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        real_spectrum_lo_i_blk_n = real_spectrum_lo_i_full_n;
    end else begin
        real_spectrum_lo_i_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter16 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        real_spectrum_lo_i_write = 1'b1;
    end else begin
        real_spectrum_lo_i_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        twid_rom_M_imag_V_ce0 = 1'b1;
    end else begin
        twid_rom_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        twid_rom_M_real_V_ce0 = 1'b1;
    end else begin
        twid_rom_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln712_fu_508_p2 = ($signed(descramble_buf_M_imag_V_load_reg_876_pp0_iter12_reg) + $signed(descramble_buf_M_real_V_load_reg_906_pp0_iter12_reg));

assign add_ln88_fu_221_p2 = (ap_sig_allocacmp_i_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((real_spectrum_lo_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((real_spectrum_lo_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((real_spectrum_lo_i_full_n == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state17_pp0_stage0_iter16 = (real_spectrum_lo_i_full_n == 1'b0);
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign descramble_buf_M_imag_V_1_address0 = zext_ln712_fu_237_p1;

assign descramble_buf_M_imag_V_address0 = zext_ln90_fu_245_p1;

assign descramble_buf_M_real_V_1_address0 = zext_ln712_reg_839_pp0_iter2_reg;

assign descramble_buf_M_real_V_address0 = zext_ln90_reg_851;

assign f_M_imag_V_fu_435_p3 = ((tmp_2_reg_928_pp0_iter6_reg[0:0] == 1'b1) ? sub_ln1201_3_fu_430_p2 : trunc_ln1201_5_reg_933_pp0_iter6_reg);

assign f_M_real_V_fu_470_p3 = ((tmp_reg_953_pp0_iter7_reg[0:0] == 1'b1) ? sub_ln1201_1_fu_465_p2 : trunc_ln1201_2_reg_958_pp0_iter7_reg);

assign g_M_imag_V_fu_481_p3 = ((tmp_4_reg_973_pp0_iter7_reg[0:0] == 1'b1) ? sub_ln1201_6_fu_476_p2 : trunc_ln1201_3_reg_978_pp0_iter7_reg);

assign g_M_real_V_fu_389_p3 = ((tmp_3_fu_366_p3[0:0] == 1'b1) ? sub_ln1201_4_fu_374_p2 : trunc_ln1201_8_fu_379_p4);

assign grp_fu_771_p0 = sext_ln1171_fu_441_p1;

assign grp_fu_771_p1 = grp_fu_771_p10;

assign grp_fu_771_p10 = w_M_real_V_reg_983;

assign grp_fu_777_p1 = sext_ln1171_fu_441_p1;

assign grp_fu_783_p0 = sext_ln1171_1_fu_487_p1;

assign grp_fu_783_p1 = zext_ln1168_reg_1015_pp0_iter8_reg;

assign grp_fu_790_p0 = sext_ln1171_2_reg_1021_pp0_iter8_reg;

assign grp_fu_790_p1 = sext_ln1171_1_fu_487_p1;

assign icmp_ln88_fu_215_p2 = ((ap_sig_allocacmp_i_2 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_254_p2 = ((i_2_reg_814_pp0_iter3_reg == 9'd0) ? 1'b1 : 1'b0);

assign p_r_M_imag_V_1_fu_528_p2 = (trunc_ln2_reg_1060 + f_M_imag_V_reg_998_pp0_iter12_reg);

assign p_r_M_real_V_1_fu_520_p2 = (p_r_V_reg_1054 + f_M_real_V_reg_1027_pp0_iter12_reg);

assign r_V_5_fu_361_p2 = (17'd0 - ret_V_8_reg_918);

assign real_spectrum_hi_buf_M_imag_V_address0 = zext_ln712_reg_839_pp0_iter15_reg;

assign real_spectrum_hi_buf_M_imag_V_d0 = select_ln1201_5_reg_1171;

assign real_spectrum_hi_buf_M_real_V_address0 = zext_ln712_reg_839_pp0_iter15_reg;

assign real_spectrum_hi_buf_M_real_V_d0 = select_ln1201_4_reg_1166;

assign real_spectrum_lo_i_din = {{select_ln1201_3_reg_1161}, {select_ln1201_reg_1156}};

assign ret_V_6_fu_322_p2 = ($signed(sext_ln1245_1_fu_310_p1) + $signed(sext_ln1245_fu_313_p1));

assign ret_V_7_fu_276_p2 = ($signed(sext_ln1245_3_fu_264_p1) + $signed(sext_ln1245_2_fu_267_p1));

assign ret_V_8_fu_270_p2 = ($signed(sext_ln1245_3_fu_264_p1) - $signed(sext_ln1245_2_fu_267_p1));

assign ret_V_9_fu_316_p2 = ($signed(sext_ln1245_1_fu_310_p1) - $signed(sext_ln1245_fu_313_p1));

assign select_ln1201_3_fu_727_p3 = ((tmp_6_reg_1111[0:0] == 1'b1) ? sub_ln1201_10_fu_722_p2 : sext_ln1201_3_fu_719_p1);

assign select_ln1201_4_fu_742_p3 = ((tmp_7_reg_1126[0:0] == 1'b1) ? sub_ln1201_12_fu_737_p2 : sext_ln1201_5_fu_734_p1);

assign select_ln1201_5_fu_757_p3 = ((tmp_8_reg_1141[0:0] == 1'b1) ? sub_ln1201_14_fu_752_p2 : sext_ln1201_7_fu_749_p1);

assign select_ln1201_fu_712_p3 = ((tmp_5_reg_1096[0:0] == 1'b1) ? sub_ln1201_8_fu_707_p2 : sext_ln1201_1_fu_704_p1);

assign sext_ln1171_1_fu_487_p1 = $signed(g_M_imag_V_reg_1033);

assign sext_ln1171_2_fu_462_p1 = w_M_imag_V_reg_988;

assign sext_ln1171_fu_441_p1 = $signed(g_M_real_V_reg_968);

assign sext_ln1201_1_fu_704_p1 = $signed(trunc_ln1201_9_reg_1106);

assign sext_ln1201_2_fu_560_p1 = t_V_5_fu_542_p3;

assign sext_ln1201_3_fu_719_p1 = $signed(trunc_ln1201_11_reg_1121);

assign sext_ln1201_4_fu_556_p1 = t_V_6_fu_537_p3;

assign sext_ln1201_5_fu_734_p1 = $signed(trunc_ln1201_13_reg_1136);

assign sext_ln1201_6_fu_552_p1 = t_V_7_fu_532_p3;

assign sext_ln1201_7_fu_749_p1 = $signed(trunc_ln1201_15_reg_1151);

assign sext_ln1201_fu_564_p1 = t_V_4_fu_547_p3;

assign sext_ln1245_1_fu_310_p1 = $signed(descramble_buf_M_real_V_1_load_1_reg_913);

assign sext_ln1245_2_fu_267_p1 = descramble_buf_M_imag_V_load_reg_876;

assign sext_ln1245_3_fu_264_p1 = $signed(sub_ln712_1_reg_891);

assign sext_ln1245_fu_313_p1 = descramble_buf_M_real_V_load_reg_906;

assign sub_ln1201_10_fu_722_p2 = (16'd0 - trunc_ln1201_10_reg_1116);

assign sub_ln1201_11_fu_644_p2 = ($signed(17'd0) - $signed(sext_ln1201_4_fu_556_p1));

assign sub_ln1201_12_fu_737_p2 = (16'd0 - trunc_ln1201_12_reg_1131);

assign sub_ln1201_13_fu_678_p2 = ($signed(17'd0) - $signed(sext_ln1201_6_fu_552_p1));

assign sub_ln1201_14_fu_752_p2 = (16'd0 - trunc_ln1201_14_reg_1146);

assign sub_ln1201_1_fu_465_p2 = (16'd0 - trunc_ln1201_1_reg_993);

assign sub_ln1201_2_fu_346_p2 = (17'd0 - ret_V_7_reg_923);

assign sub_ln1201_3_fu_430_p2 = (16'd0 - trunc_ln1201_4_reg_963);

assign sub_ln1201_4_fu_374_p2 = (16'd0 - trunc_ln1201_7_reg_938);

assign sub_ln1201_5_fu_444_p2 = (17'd0 - ret_V_9_reg_943);

assign sub_ln1201_6_fu_476_p2 = (16'd0 - trunc_ln1201_s_reg_1010);

assign sub_ln1201_7_fu_576_p2 = ($signed(17'd0) - $signed(sext_ln1201_fu_564_p1));

assign sub_ln1201_8_fu_707_p2 = (16'd0 - trunc_ln1201_6_reg_1101);

assign sub_ln1201_9_fu_610_p2 = ($signed(17'd0) - $signed(sext_ln1201_2_fu_560_p1));

assign sub_ln1201_fu_415_p2 = (17'd0 - ret_V_6_reg_948);

assign sub_ln712_1_fu_259_p2 = (16'd0 - descramble_buf_M_imag_V_1_load_1_reg_866);

assign sub_ln712_2_fu_516_p2 = (f_M_real_V_reg_1027_pp0_iter12_reg - p_r_V_reg_1054);

assign sub_ln712_3_fu_524_p2 = (trunc_ln2_reg_1060 - f_M_imag_V_reg_998_pp0_iter12_reg);

assign sub_ln712_4_fu_231_p2 = (8'd0 - trunc_ln88_fu_227_p1);

assign sub_ln712_fu_512_p2 = ($signed(descramble_buf_M_real_V_load_reg_906_pp0_iter12_reg) - $signed(descramble_buf_M_imag_V_load_reg_876_pp0_iter12_reg));

assign t_V_4_fu_547_p3 = ((icmp_ln92_reg_883_pp0_iter13_reg[0:0] == 1'b1) ? add_ln712_reg_1066 : p_r_M_real_V_1_reg_1081);

assign t_V_5_fu_542_p3 = ((icmp_ln92_reg_883_pp0_iter13_reg[0:0] == 1'b1) ? sub_ln712_reg_1071 : p_r_M_imag_V_1_reg_1091);

assign t_V_6_fu_537_p3 = ((icmp_ln92_reg_883_pp0_iter13_reg[0:0] == 1'b1) ? descramble_buf_M_real_V_1_load : sub_ln712_2_reg_1076);

assign t_V_7_fu_532_p3 = ((icmp_ln92_reg_883_pp0_iter13_reg[0:0] == 1'b1) ? descramble_buf_M_imag_V_1_load : sub_ln712_3_reg_1086);

assign tmp_3_fu_366_p3 = r_V_5_fu_361_p2[32'd16];

assign trunc_ln1201_8_fu_379_p4 = {{r_V_5_fu_361_p2[16:1]}};

assign trunc_ln88_fu_227_p1 = ap_sig_allocacmp_i_2[7:0];

assign twid_rom_M_imag_V_address0 = zext_ln88_fu_249_p1;

assign twid_rom_M_real_V_address0 = zext_ln88_fu_249_p1;

assign zext_ln1168_fu_459_p1 = w_M_real_V_reg_983;

assign zext_ln712_fu_237_p1 = sub_ln712_4_reg_834;

assign zext_ln88_fu_249_p1 = i_2_reg_814_pp0_iter3_reg;

assign zext_ln90_fu_245_p1 = trunc_ln88_reg_829_pp0_iter1_reg;

always @ (posedge ap_clk) begin
    zext_ln712_reg_839[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter2_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter3_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter4_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter5_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter6_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter7_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter8_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter9_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter10_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter11_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter12_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter13_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter14_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln712_reg_839_pp0_iter15_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln90_reg_851[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln1168_reg_1015[30:15] <= 16'b0000000000000000;
    zext_ln1168_reg_1015_pp0_iter8_reg[30:15] <= 16'b0000000000000000;
end

endmodule //hls_xfft2real_Loop_realfft_be_descramble_proc2_Pipeline_realfft_be_descramble
